name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get the latest commit hash
        id: get_commit
        run: echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_commit.outputs.commit }}
          release_name: Release ${{ steps.get_commit.outputs.commit }}
          draft: false
          prerelease: false
